
IMAGE_SIZE = (224, 224)
NUM_REGIONS = 16
HASH_SIZE = 64
HAMMING_THRESHOLD = 20
TOP_N_MATCHES = 5
CLAHE_CLIP_LIMIT = 2.0
CLAHE_GRID_SIZE = (8, 8)

USE_FULL_PREPROCESSING = False  
USE_CLAHE = True
USE_DENOISING = False 
USE_SHARPENING = False

USE_GPU = True
GPU_ID = 0  
BATCH_SIZE = 32 
